name: Sync from Bitbucket to GitHub

on:
  push:
    branches:
      - 'main'
      - 'develop'  # You can list other branches as well

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "action@github.com"

    - name: Add Bitbucket as remote
      run: |
        git remote add bitbucket https://succpinnsolutions:ATBBeuBWUpFyNBcyWNDmw9cG4Vr9DE8CA653@bitbucket.org/succpinnsolutions/ecommerapp.git
        git fetch bitbucket

    - name: Pull and push changes to GitHub
      run: |
        git pull bitbucket main
        git push github main
