name: Sync to GitHub

on:
  # Triggers the workflow on push events
  push:
    branches:
      - main  # or master, depending on your default branch
      
  # Allows manual trigger
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
      - name: Add Bitbucket Remote
        run: |
          git remote add bitbucket https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_PASSWORD }}@bitbucket.org/succpinnsolutions/ecommerapp.git 
      - name: Fetch from Bitbucket
        run: |
          git fetch bitbucket
          
      - name: Sync Changes
        run: |
          git checkout main
          git merge bitbucket/main
          git push origin main
