name: Mirror Bitbucket to GitHub

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes (adjust as needed)
  workflow_dispatch: # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important: Fetches all history

      - name: Mirror to GitHub
        run: |
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch bitbucket  https://succpinnsolutions-admin@bitbucket.org/succpinnsolutions/ecommerapp.git # Fetch changes from Bitbucket
          git push --mirror origin
        env:
          BITBUCKET_USERNAME: succpinnsolutions-admin
          BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
